"""Removed testandtrial col

Revision ID: 97e098576bc8
Revises: d5603dd1dd12
Create Date: 2025-02-19 15:36:54.130352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e098576bc8'
down_revision: Union[str, None] = 'd5603dd1dd12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controlobjective', 'testandtrial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controlobjective', sa.Column('testandtrial', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
