"""added exception db

Revision ID: a7c240e67fa6
Revises: 97e098576bc8
Create Date: 2025-02-26 14:14:52.102703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'a7c240e67fa6'
down_revision: Union[str, None] = '97e098576bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlexception',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('soc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('controls_specified', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tests', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('results', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('servicer_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deficiency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mitigating_controls', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controlexception')
    # ### end Alembic commands ###
