"""Added testandtrial column

Revision ID: d5603dd1dd12
Revises: a81b27a21a3a
Create Date: 2025-02-19 15:34:48.684544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5603dd1dd12'
down_revision: Union[str, None] = 'a81b27a21a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controlobjective', sa.Column('testandtrial', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controlobjective', 'testandtrial')
    # ### end Alembic commands ###
